name: Periodic CI check
on:
  schedule:
    - cron: "0 0 * * 1" # every Monday at midnight
  workflow_dispatch: {} # allow triggering the workflow manually
jobs:
  periodic_ci:
    runs-on: "ubuntu-latest"
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          repository: openshift/cluster-samples-operator
      - name: run library-sync.sh
        run: "./library-sync.sh"
      - name: periodic-ci pull request
        id: cpr
        uses: peter-evans/create-pull-request@v7
        with:
          branch: periodic-ci
          delete-branch: true
          title: "Periodic CI check"
          body: |
            Periodic check for library sync compatibility
          token: ${{ secrets.PR_TOKEN }}
          push-to-fork: metlos/cluster-samples-operator
      - uses: actions/github-script@v7
        with:
          github-token: ${{secrets.PR_TOKEN}}
          script: |
            github.rest.issues.createComment({
              issue_number: ${{ steps.cpr.outputs.pull-request-number}},
              owner: "openshift",
              repo: "cluster-samples-operator",
              body: "/hold\n\nThis PR is not meant for merging. It merely checks whether the Samples Operator builds with the rest of the Openshift ecosystem."
            })
